version: "3.9"

services:
  sf-demo:
    image: stock-finder-service-demo
    networks:
      stock_finder_net:
        ipv4_address: 172.28.1.3
    ports:
      - "8080:8080"

networks:
  stock_finder_net:
    external: true